### ISSUE TITLE
Multi-language sites

### ISSUE THREAD

**Issue by theamnesic** [johannschopplich/kirby-locked-pages#10]
Hi!

When you change the URL of the default language (fr), for exemple with `'url' => '/'` to hide the default language in the URL, the redirection give a 404, trying to go to `/fr/locked?redirect=espace-prive` instead of `/locked?redirect=espace-prive`.

I don't know if it's possible for you to deal with [specific URLs](https://getkirby.com/docs/guide/languages/introduction#language-specific-urls) ?

Thanks!

**Comment by johannschopplich** [comment]
Hi there,

thanks for the bug report. I'm not actively developing this plugin anymore. Thus, I probably won't fix your request. But I will happily accept a PR!
You have to adapt the generated URL here: https://github.com/johannschopplich/kirby-locked-pages/blob/7dceaf9c4af6c4cd3a7a90b9d857a55e770cc1fe/extensions/hooks.php#L20

**Comment by tobimori** [comment]
Same issue, will submit a PR tomorrow. :)
