### ISSUE TITLE
Password-protection not working on homepage 

### ISSUE THREAD

**Issue by g5604** [johannschopplich/kirby-locked-pages#3]
Thanks for this, just what I need. 

I installed via composer, the form shows correctly (using on home page) and the url changes to mysite.com/locked?redirect= but when I put in the correct password the page just reloads, no error message - any ideas?

**Comment by g5604** [comment]
Ah ok - it works on sub pages, but not the home page.

**Comment by g5604** [comment]
Why is it not possible to lock the home page?

**Comment by johannschopplich** [comment]
May I ask what your use case for locking the homepage is? It's possible to implement; I just see no case of application at the moment. Would you like to lock the whole Kirby instnace?

**Comment by g5604** [comment]
I have a client that want's a site that is not shared with wider world, only their employees with one shared password. The site is also blocked from search engines. I have had this before a few times over the years, I guess it's quite common for large organisations to have these internal micro sites?  I only need the plugin to work the same as it does on sub pages.  Thanks!

**Comment by johannschopplich** [comment]
Good point. Thanks for the comprehensive explanation!

**Comment by johannschopplich** [comment]
Made possible by https://github.com/johannschopplich/kirby-locked-pages/commit/2f85e06a49018eeee58478f6dadfeb1ec0f6f5c6.

Also pushed v1.2.0.

**Comment by g5604** [comment]
Amazing, thank you :)
