### ISSUE TITLE
Feature request: add logout option

### ISSUE THREAD

**Issue by VIPStephan** [johannschopplich/kirby-locked-pages#4]
This is a very nice plugin. The only thing I wish for (at the moment) would be a way to end the session manually, i. e. have a logout link that removes the specific session data.

**Comment by johannschopplich** [comment]
Good idea! I've created a custom logout hook: https://github.com/johannschopplich/kirby-locked-pages/releases/tag/v1.3.0

Trigger the `locked-pages.logout` hook to clear the locked pages' session data. Once logged out, the user will have to enter the password again to visit the locked page.

```php
kirby()->trigger('locked-pages.logout');
```

New release ready to test: https://github.com/johannschopplich/kirby-locked-pages/releases/tag/v1.3.0

Could you please give feedback, if that works for you?

**Comment by VIPStephan** [comment]
Wow, man, that was a quick turnaround! Thanks, man. :)
However, if I replace the plugin files with the new version I get the error

> TypeError thrown with message "Argument 2 passed to Kirby\Cms\Event::call() must be an instance of Closure, string given, called in ~/kirby/src/Cms/App.php on line 203"
> 
> Stacktrace:
> #6 TypeError in ~/kirby/src/Cms/Event.php:161
> #5 Kirby\Cms\Event:call in ~/kirby/src/Cms/App.php:203
> #4 Kirby\Cms\App:apply in ~/kirby/src/Cms/App.php:334
> #3 Kirby\Cms\App:Kirby\Cms\{closure} in ~/kirby/src/Http/Router.php:117
> #2 Kirby\Http\Router:call in ~/kirby/src/Cms/App.php:337
> #1 Kirby\Cms\App:call in ~/kirby/src/Cms/App.php:1040
> #0 Kirby\Cms\App:render in ~/index.php:5

Is it a bug or is it me being stupid?

**Comment by johannschopplich** [comment]
You're welcome. 🙂 

My bad, I did break the plugin with the last release. Fixed now. Could you please test again?

**Comment by VIPStephan** [comment]
Thanks, you’re awesome! :)
