### ISSUE TITLE
Missing multilingualism

### ISSUE THREAD

**Issue by derunterstrich** [johannschopplich/kirby-locked-pages#7]
Hi,

I noticed in a project that this great plug-in unfortunately does not support the multilingual function. Can you fix that? Should I try my hand at it? If second, would you rather do it as a fork or as PR?

Greetings
Tobias

**Comment by johannschopplich** [comment]
Hi Tobias, I don't have the time to look into it currently. Feel free to provide a PR, sure!

**Comment by derunterstrich** [comment]
Hi johannschopplich,

I have tried, but I cannot create a new branch.
The changes are very simple:

**File: hooks.php**

replace 
`        $slug    = option('johannschopplich.locked-pages.slug', 'locked');`

with:

`global $kirby;

        $slug = '';
        if (option('johannschopplich.locked-pages.languages', false) && !empty($kirby->languageCode())) {
            $slug = $kirby->languageCode() . '/';
        }

        $slug    .= option('johannschopplich.locked-pages.slug', 'locked');`

**File: readme**
| `languages` | `false`| Activates the language check before redirect. |
