### ISSUE TITLE
 ArgumentCountError Too few arguments to function Kirby\Cms\App::{closure}(), 4 passed and exactly 5 expected

### ISSUE THREAD

**Issue by mitch-spec** [johannschopplich/kirby-locked-pages#9]
I installed the library on Kirby 3.3.2 and PHP 7-73STABLE-STANDARD and the site does not render anymore. When debugging is enabled i get the following error message:

**ArgumentCountError Too few arguments to function Kirby\Cms\App::{closure}(), 4 passed and exactly 5 expected**

_kirby/site/plugins/kirby-locked-pages/extensions/hooks.php_

```
<?php
 
use JohannSchopplich\LockedPages;
 
return [
    'route:after' => function ($route, $path, $method, $result, $final) {
```

Do you have any suggestion how to solve this error?

**Comment by johannschopplich** [comment]
This is connected to the outdated Kirby version. Could you please update to 3.7+? Thanks!

Your version is outdated for some years…
